
export const layouts = {
    modern: {
      container: "max-w-none dark:prose-invert",
      header: "mb-8 bg-gray-50 dark:bg-gray-800 p-6 rounded-lg",
      headerContent: "text-center",
      name: "text-3xl font-bold mb-2 text-primary",
      contact: "text-sm text-gray-600 dark:text-gray-400 space-y-1",
      section: "mb-8",
      sectionTitle: "text-xl font-bold mb-4 text-primary border-b pb-2",
      itemTitle: "font-bold text-gray-800 dark:text-gray-200",
      itemSubtitle: "text-sm text-gray-600 dark:text-gray-400",
      itemDate: "text-sm text-gray-600 dark:text-gray-400 italics",
      description: "mt-2 text-sm text-gray-700 dark:text-gray-300",
      skills: "flex flex-wrap gap-2",
      skill: "px-3 py-1 bg-primary/10 rounded-full text-sm text-primary",
      bulletPointContainer:"list-disc list-inside text-sm text-gray-600 mt-4",
      bulletPoint:""
    },
    classic: {
      container: "max-w-none dark:prose-invert",
      header: "mb-8 border-b-2 pb-6",
      headerContent: "text-left",
      name: "text-4xl font-serif mb-2",
      contact: "text-sm space-y-1",
      section: "mb-8",
      sectionTitle: "text-2xl font-serif mb-4 text-gray-800 dark:text-gray-200",
      itemTitle: "font-serif font-bold",
      itemSubtitle: "text-sm",
      itemDate: "text-sm italic",
      description: "mt-2 text-sm",
      skills: "grid grid-cols-2 gap-2",
      skill: "text-sm",
      bulletPointContainer:"list-disc list-inside text-sm text-gray-600 mt-4",
      bulletPoint:""
    },
    minimal: {
      container: "max-w-none dark:prose-invert",
      header: "mb-8",
      headerContent: "space-y-2",
      name: "text-2xl font-bold",
      contact: "text-sm flex flex-wrap gap-4",
      section: "mb-6",
      sectionTitle: "text-lg font-bold mb-3 uppercase tracking-wide",
      itemTitle: "font-medium",
      itemSubtitle: "text-sm",
      itemDate: "text-sm text-gray-600 dark:text-gray-400",
      description: "mt-2 text-sm",
      skills: "flex flex-wrap gap-4",
      skill: "text-sm",
      bulletPointContainer:"list-disc list-inside text-sm text-gray-600 mt-4",
      bulletPoint:""
    },
    contemporary: {
      container: "max-w-none dark:prose-invert",
      header:
        "mb-8 bg-gradient-to-r from-primary to-blue-500 text-white p-6 rounded-lg",
      headerContent: "text-center",
      name: "text-4xl font-bold mb-2",
      contact: "text-sm space-y-1",
      section: "mb-8",
      sectionTitle: "text-2xl font-bold mb-4 border-b-2 pb-2 text-primary",
      itemTitle: "font-semibold text-gray-800 dark:text-gray-200",
      itemSubtitle: "text-sm italic text-gray-600 dark:text-gray-400",
      itemDate: "text-sm italic text-gray-500 dark:text-gray-400",
      description: "mt-2 text-sm leading-relaxed",
      skills: "flex flex-wrap gap-2",
      skill: "px-3 py-1 bg-blue-100 rounded-full text-sm text-blue-700",
      bulletPointContainer:"list-disc list-inside text-sm text-gray-600 mt-4",
      bulletPoint:""
    },
    elegant: {
      container: "max-w-none dark:prose-invert",
      header: "mb-8 border-b pb-6 text-center",
      headerContent: "text-center space-y-2",
      name: "text-5xl font-light tracking-wider",
      contact: "text-sm italic",
      section: "mb-8",
      sectionTitle: "text-2xl font-light mb-4 border-b pb-2",
      itemTitle: "font-semibold text-lg",
      itemSubtitle: "text-sm text-gray-600 dark:text-gray-400",
      itemDate: "text-sm text-gray-500 dark:text-gray-400 italic",
      description: "mt-2 text-sm",
      skills: "flex flex-wrap gap-2 justify-center",
      skill: "text-sm border border-gray-300 px-3 py-1 rounded-full",
      bulletPointContainer:"list-disc list-inside text-sm text-gray-600 mt-4",
      bulletPoint:""
    },
    creative: {
      container: "max-w-none dark:prose-invert",
      header: "mb-8 bg-primary text-white p-6 rounded-lg",
      headerContent: "text-left",
      name: "text-4xl font-extrabold",
      contact: "text-sm flex flex-col space-y-1",
      section: "mb-8",
      sectionTitle: "text-2xl font-extrabold mb-4 text-primary",
      itemTitle: "font-bold",
      itemSubtitle: "text-sm italic",
      itemDate: "text-sm text-gray-600 dark:text-gray-400 italic",
      description: "mt-2 text-sm leading-6",
      skills: "grid grid-cols-3 gap-2",
      skill: "px-2 py-1 bg-primary text-white rounded-lg text-sm",
      bulletPointContainer:"list-disc list-inside text-sm text-gray-600 mt-4",
      bulletPoint:""
    },
      /** New Two-Column Modern Layout */
      twoColumnModern: {
        container: "grid grid-cols-2 gap-8 max-w-none dark:prose-invert",
        header: "col-span-2 mb-8 bg-gray-50 dark:bg-gray-800 p-6 rounded-lg",
        headerContent: "text-center",
        name: "text-3xl font-bold mb-2 text-primary",
        contact: "text-sm text-gray-600 dark:text-gray-400 space-y-1",
        section: "mb-8 col-span-1",
        sectionTitle: "text-xl font-bold mb-4 text-primary border-b pb-2",
        itemTitle: "font-bold text-gray-800 dark:text-gray-200",
        itemSubtitle: "text-sm text-gray-600 dark:text-gray-400",
        itemDate: "text-sm text-gray-600 dark:text-gray-400 italic",
        description: "mt-2 text-sm text-gray-700 dark:text-gray-300",
        skills: "flex flex-wrap gap-2 col-span-1",
        skill: "px-3 py-1 bg-primary/10 rounded-full text-sm text-primary",
        bulletPointContainer:"list-disc list-inside text-sm text-gray-600 mt-4",
        bulletPoint:""
    },
    /** New Two-Column Professional Layout */
    twoColumnProfessional: {
        container: "grid grid-cols-[1fr_2fr] gap-8 max-w-none dark:prose-invert",
        header: "col-span-2 mb-8 border-b-2 pb-6",
        headerContent: "text-left",
        name: "text-4xl font-bold",
        contact: "text-sm space-y-1",
        section: "mb-8 col-span-2",
        sectionTitle: "text-2xl font-bold mb-4 text-gray-800 dark:text-gray-200",
        itemTitle: "font-bold",
        itemSubtitle: "text-sm",
        itemDate: "text-sm italic",
        description: "mt-2 text-sm",
        skills: "flex flex-wrap gap-4 col-span-1",
        skill: "text-sm",
        bulletPointContainer:"list-disc list-inside text-sm text-gray-600 mt-4",
        bulletPoint:""
    }
  };